//! Documentation output generation (Markdown, HTML, JSON, Mermaid, SQL).

#[cfg(feature = "experimental")]
use crate::SqlDialect;
use crate::redaction::Redactor;
use crate::{Cli, OutputFormat, RedactionMode, create_spinner, schema};
use dbsurveyor_core::{Result, models::DatabaseSchema};
use std::path::PathBuf;
use tracing::{info, warn};

/// Generates documentation from schema.
pub(crate) async fn generate_documentation(
    input_path: &PathBuf,
    format: OutputFormat,
    output_path: Option<&PathBuf>,
    cli: &Cli,
) -> Result<()> {
    let schema = schema::load_schema(input_path).await?;

    info!("Loaded schema for database: {}", schema.database_info.name);
    info!("Format version: {}", schema.format_version);
    info!("Tables: {}", schema.tables.len());

    // Apply redaction to samples if present
    let redact_mode = if cli.no_redact {
        RedactionMode::None
    } else {
        cli.redact_mode.clone()
    };

    let _redacted_samples = if let Some(ref samples) = schema.samples {
        let redactor = Redactor::new(redact_mode);
        Some(redactor.redact(samples))
    } else {
        None
    };

    let output_file = match output_path {
        Some(path) => path.clone(),
        None => {
            let base_name = input_path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("schema");

            match format {
                OutputFormat::Markdown => format!("{}.md", base_name).into(),
                #[cfg(feature = "experimental")]
                OutputFormat::Html => format!("{}.html", base_name).into(),
                #[cfg(feature = "experimental")]
                OutputFormat::Json => format!("{}_analysis.json", base_name).into(),
                #[cfg(feature = "experimental")]
                OutputFormat::Mermaid => format!("{}.mmd", base_name).into(),
            }
        }
    };

    let format_name = match format {
        OutputFormat::Markdown => "markdown",
        #[cfg(feature = "experimental")]
        OutputFormat::Html => "HTML",
        #[cfg(feature = "experimental")]
        OutputFormat::Json => "JSON",
        #[cfg(feature = "experimental")]
        OutputFormat::Mermaid => "Mermaid",
    };
    let spinner = create_spinner(&format!("Generating {} documentation...", format_name));

    let gen_result = match format {
        OutputFormat::Markdown => generate_markdown(&schema, &output_file).await,
        #[cfg(feature = "experimental")]
        OutputFormat::Html => generate_html(&schema, &output_file).await,
        #[cfg(feature = "experimental")]
        OutputFormat::Json => generate_json_analysis(&schema, &output_file).await,
        #[cfg(feature = "experimental")]
        OutputFormat::Mermaid => generate_mermaid(&schema, &output_file).await,
    };

    spinner.finish_and_clear();
    gen_result?;
    info!("[OK]Documentation generated: {}", output_file.display());
    println!("Documentation generated: {}", output_file.display());

    Ok(())
}

/// Generates Markdown documentation (placeholder).
async fn generate_markdown(schema: &DatabaseSchema, output_path: &PathBuf) -> Result<()> {
    let content = format!(
        "# Database Schema: {}\n\n\
        Generated by DBSurveyor v{}\n\
        Collection Date: {}\n\n\
        ## Summary\n\n\
        - **Tables**: {}\n\
        - **Views**: {}\n\
        - **Indexes**: {}\n\n\
        ## Tables\n\n",
        schema.database_info.name,
        schema.collection_metadata.collector_version,
        schema
            .collection_metadata
            .collected_at
            .format("%Y-%m-%d %H:%M:%S UTC"),
        schema.tables.len(),
        schema.views.len(),
        schema.indexes.len()
    );

    tokio::fs::write(output_path, content).await.map_err(|e| {
        dbsurveyor_core::error::DbSurveyorError::Io {
            context: format!("Failed to write Markdown to {}", output_path.display()),
            source: e,
        }
    })?;

    Ok(())
}

#[cfg(feature = "experimental")]
/// Generates HTML documentation (placeholder).
async fn generate_html(_schema: &DatabaseSchema, output_path: &PathBuf) -> Result<()> {
    let content = "<!DOCTYPE html><html><head><title>Database Schema</title></head><body><h1>Schema Documentation</h1><p>HTML generation not yet implemented</p></body></html>";

    tokio::fs::write(output_path, content).await.map_err(|e| {
        dbsurveyor_core::error::DbSurveyorError::Io {
            context: format!("Failed to write HTML to {}", output_path.display()),
            source: e,
        }
    })?;

    Ok(())
}

#[cfg(feature = "experimental")]
/// Generates JSON analysis (placeholder).
async fn generate_json_analysis(schema: &DatabaseSchema, output_path: &PathBuf) -> Result<()> {
    let analysis = serde_json::json!({
        "database_name": schema.database_info.name,
        "table_count": schema.tables.len(),
        "view_count": schema.views.len(),
        "index_count": schema.indexes.len(),
        "collection_date": schema.collection_metadata.collected_at
    });

    let file = std::fs::File::create(output_path).map_err(|e| {
        dbsurveyor_core::error::DbSurveyorError::Io {
            context: format!("Failed to create {}", output_path.display()),
            source: e,
        }
    })?;
    let writer = std::io::BufWriter::new(file);
    serde_json::to_writer_pretty(writer, &analysis).map_err(|e| {
        dbsurveyor_core::error::DbSurveyorError::Serialization {
            context: "Failed to serialize analysis".to_string(),
            source: e,
        }
    })?;

    Ok(())
}

#[cfg(feature = "experimental")]
/// Generates Mermaid ERD (placeholder).
async fn generate_mermaid(_schema: &DatabaseSchema, output_path: &PathBuf) -> Result<()> {
    let content = "erDiagram\n    %% Mermaid ERD generation not yet implemented\n    PLACEHOLDER {\n        string note\n    }";

    tokio::fs::write(output_path, content).await.map_err(|e| {
        dbsurveyor_core::error::DbSurveyorError::Io {
            context: format!("Failed to write Mermaid to {}", output_path.display()),
            source: e,
        }
    })?;

    Ok(())
}

#[cfg(feature = "experimental")]
/// Analyzes schema for insights (placeholder).
pub(crate) async fn analyze_schema(input_path: &PathBuf, detailed: bool) -> Result<()> {
    let schema = schema::load_schema(input_path).await?;

    println!("Schema Analysis: {}", schema.database_info.name);
    println!("================");
    println!("Tables: {}", schema.tables.len());
    println!("Views: {}", schema.views.len());
    println!("Indexes: {}", schema.indexes.len());
    println!("Constraints: {}", schema.constraints.len());

    if detailed {
        println!("\nDetailed Analysis:");
        println!("- Procedures: {}", schema.procedures.len());
        println!("- Functions: {}", schema.functions.len());
        println!("- Triggers: {}", schema.triggers.len());
        println!("- Custom Types: {}", schema.custom_types.len());
    }

    Ok(())
}

#[cfg(feature = "experimental")]
/// Generates SQL DDL (placeholder).
pub(crate) async fn generate_sql(
    input_path: &PathBuf,
    _dialect: SqlDialect,
    output_path: Option<&PathBuf>,
) -> Result<()> {
    warn!("SQL DDL generation is not yet fully implemented. Output will be minimal.");
    warn!("--dialect is not yet implemented and will be ignored");
    let schema = schema::load_schema(input_path).await?;

    let sql_content = format!(
        "-- Database Schema: {}\n\
        -- Generated by DBSurveyor\n\n\
        -- SQL DDL generation not yet implemented\n\
        -- Tables: {}\n",
        schema.database_info.name,
        schema.tables.len()
    );

    let output_file = match output_path {
        Some(path) => path.clone(),
        None => {
            let base_name = input_path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("schema");
            format!("{}.sql", base_name).into()
        }
    };

    tokio::fs::write(&output_file, sql_content)
        .await
        .map_err(|e| dbsurveyor_core::error::DbSurveyorError::Io {
            context: format!("Failed to write SQL to {}", output_file.display()),
            source: e,
        })?;

    println!("SQL DDL generated: {}", output_file.display());
    Ok(())
}

/// Validates schema file format.
pub(crate) async fn validate_schema(input_path: &PathBuf) -> Result<()> {
    let schema = schema::load_schema(input_path).await?;

    println!("[OK]Schema file is valid");
    println!("Format version: {}", schema.format_version);
    println!("Database: {}", schema.database_info.name);
    println!("Objects: {}", schema.object_count());

    if !schema.collection_metadata.warnings.is_empty() {
        println!("\nWarnings from collection:");
        for warning in &schema.collection_metadata.warnings {
            println!("  - {}", warning);
        }
    }

    Ok(())
}
