version: 2
updates:
  # Rust dependencies via Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps): "
      include: "scope"
    reviewers:
      - "UncleSp1d3r"
    labels:
      - "dependencies"
      - "rust"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps): "
      include: "scope"
    reviewers:
      - "UncleSp1d3r"
    labels:
      - "dependencies"
      - "ci"
