# Goodcheck configuration for DBSurveyor
# Repository quality checks and custom rules

rules:
  # Check for hardcoded credentials
  - id: hardcoded-credentials
    pattern:
      - token: "(?i)(password|secret|key|token)\\s*=\\s*['\"][^'\"]+['\"]"
        message: "Potential hardcoded credential found"
        severity: error

  # Check for TODO comments in production code
  - id: todo-comments
    pattern:
      - token: "(?i)TODO\\s*:"
        message: "TODO comment found - should be addressed before production"
        severity: warning

  # Check for debug/print statements
  - id: debug-statements
    pattern:
      - token: "(?i)(println!|print!|dbg!|eprintln!)"
        message: "Debug statement found - should be removed for production"
        severity: warning

  # Check for unsafe code usage
  - id: unsafe-usage
    pattern:
      - token: "unsafe\\s*\\{"
        message: "Unsafe code block found - review security implications"
        severity: error
