# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
#
# GoReleaser v2 configuration for DBSurveyor
#
# Builds multiple variants of dbsurveyor-collect, each with a different
# database driver feature set, plus a single dbsurveyor postprocessor.
# Uses cargo-zigbuild for cross-compilation.
#
# Variants: all, postgresql, mysql, sqlite, mongodb, mssql
# Each single-DB variant includes compression + encryption support.
#
# Reference: https://goreleaser.com/customization/builds/rust/

version: 2

project_name: dbsurveyor

before:
  hooks:
    - cargo fetch --locked

# ---------------------------------------------------------------------------
# Targets (shared across all builds)
# ---------------------------------------------------------------------------
# x86_64-unknown-linux-gnu    Linux x86_64
# aarch64-unknown-linux-gnu   Linux ARM64
# x86_64-unknown-linux-musl   Linux x86_64 (static/Alpine)
# x86_64-apple-darwin         macOS Intel
# aarch64-apple-darwin         macOS Apple Silicon
# x86_64-pc-windows-gnu       Windows x86_64

# ---------------------------------------------------------------------------
# Builds
# ---------------------------------------------------------------------------
builds:
  # -------------------------------------------------------------------------
  # Postprocessor (single build, all features)
  # -------------------------------------------------------------------------
  - id: dbsurveyor
    builder: rust
    dir: .
    binary: dbsurveyor
    command: zigbuild
    flags:
      - --release
      - --locked
      - --all-features
      - -p=dbsurveyor
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
    mod_timestamp: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # Collector: all features (all database drivers)
  # -------------------------------------------------------------------------
  - id: collect-all
    builder: rust
    dir: .
    binary: dbsurveyor-collect
    command: zigbuild
    flags:
      - --release
      - --locked
      - --all-features
      - -p=dbsurveyor-collect
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
    mod_timestamp: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # Collector: PostgreSQL only
  # -------------------------------------------------------------------------
  - id: collect-postgresql
    builder: rust
    dir: .
    binary: dbsurveyor-collect
    command: zigbuild
    flags:
      - --release
      - --locked
      - --no-default-features
      - --features=postgresql,compression,encryption
      - -p=dbsurveyor-collect
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
    mod_timestamp: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # Collector: MySQL only
  # -------------------------------------------------------------------------
  - id: collect-mysql
    builder: rust
    dir: .
    binary: dbsurveyor-collect
    command: zigbuild
    flags:
      - --release
      - --locked
      - --no-default-features
      - --features=mysql,compression,encryption
      - -p=dbsurveyor-collect
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
    mod_timestamp: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # Collector: SQLite only
  # -------------------------------------------------------------------------
  - id: collect-sqlite
    builder: rust
    dir: .
    binary: dbsurveyor-collect
    command: zigbuild
    flags:
      - --release
      - --locked
      - --no-default-features
      - --features=sqlite,compression,encryption
      - -p=dbsurveyor-collect
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
    mod_timestamp: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # Collector: MongoDB only
  # -------------------------------------------------------------------------
  - id: collect-mongodb
    builder: rust
    dir: .
    binary: dbsurveyor-collect
    command: zigbuild
    flags:
      - --release
      - --locked
      - --no-default-features
      - --features=mongodb,compression,encryption
      - -p=dbsurveyor-collect
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
    mod_timestamp: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # Collector: MSSQL only
  # -------------------------------------------------------------------------
  - id: collect-mssql
    builder: rust
    dir: .
    binary: dbsurveyor-collect
    command: zigbuild
    flags:
      - --release
      - --locked
      - --no-default-features
      - --features=mssql,compression,encryption
      - -p=dbsurveyor-collect
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
    mod_timestamp: "{{ .CommitTimestamp }}"

# ---------------------------------------------------------------------------
# Archives
#
# Each variant bundles the dbsurveyor postprocessor with the variant-specific
# dbsurveyor-collect binary. Archive naming: dbsurveyor_<variant>_<Os>_<Arch>
# ---------------------------------------------------------------------------
archives:
  # -------------------------------------------------------------------------
  # All-features variant (primary)
  # -------------------------------------------------------------------------
  - id: archive-all
    ids:
      - dbsurveyor
      - collect-all
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_all_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README.md
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # PostgreSQL variant
  # -------------------------------------------------------------------------
  - id: archive-postgresql
    ids:
      - dbsurveyor
      - collect-postgresql
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_postgresql_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README.md
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # MySQL variant
  # -------------------------------------------------------------------------
  - id: archive-mysql
    ids:
      - dbsurveyor
      - collect-mysql
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_mysql_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README.md
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # SQLite variant
  # -------------------------------------------------------------------------
  - id: archive-sqlite
    ids:
      - dbsurveyor
      - collect-sqlite
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_sqlite_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README.md
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # MongoDB variant
  # -------------------------------------------------------------------------
  - id: archive-mongodb
    ids:
      - dbsurveyor
      - collect-mongodb
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_mongodb_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README.md
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

  # -------------------------------------------------------------------------
  # MSSQL variant
  # -------------------------------------------------------------------------
  - id: archive-mssql
    ids:
      - dbsurveyor
      - collect-mssql
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_mssql_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README.md
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

# ---------------------------------------------------------------------------
# Checksums
# ---------------------------------------------------------------------------
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# ---------------------------------------------------------------------------
# Changelog
# ---------------------------------------------------------------------------
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^style:"

# ---------------------------------------------------------------------------
# SBOM (Software Bill of Materials)
# ---------------------------------------------------------------------------
sboms:
  - artifacts: archive

# ---------------------------------------------------------------------------
# Signing (Cosign keyless)
# ---------------------------------------------------------------------------
signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

# ---------------------------------------------------------------------------
# Linux Packages (all-features only)
# ---------------------------------------------------------------------------
nfpms:
  - id: nfpm-all
    ids:
      - dbsurveyor
      - collect-all
    file_name_template: "{{ .ConventionalFileName }}"
    maintainer: UncleSp1d3r
    homepage: https://evilbitlabs.io/dbsurveyor
    description: Secure database schema documentation and analysis tool (all database drivers)
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

# ---------------------------------------------------------------------------
# Homebrew Cask (all-features only)
# ---------------------------------------------------------------------------
homebrew_casks:
  - name: dbsurveyor
    ids:
      - archive-all
    repository:
      owner: EvilBit-Labs
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://evilbitlabs.io/dbsurveyor
    description: Secure database schema documentation and analysis tool (all database drivers)
    binaries:
      - dbsurveyor
      - dbsurveyor-collect
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore(brew): update {{ .ProjectName }} cask to {{ .Tag }}"

# ---------------------------------------------------------------------------
# Release
# ---------------------------------------------------------------------------
release:
  github:
    owner: EvilBit-Labs
    name: dbsurveyor
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/EvilBit-Labs/dbsurveyor/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Release Variants

    Each variant includes the `dbsurveyor` postprocessor and a `dbsurveyor-collect`
    binary built with the specified database driver. All variants include compression
    and encryption support.

    | Variant | Database Drivers |
    |---------|-----------------|
    | `all` | PostgreSQL, MySQL, SQLite, MongoDB, MSSQL |
    | `postgresql` | PostgreSQL only |
    | `mysql` | MySQL only |
    | `sqlite` | SQLite only |
    | `mongodb` | MongoDB only |
    | `mssql` | MSSQL only |

    ## Installation

    ### Homebrew (macOS / Linux)
    ```bash
    brew install EvilBit-Labs/tap/dbsurveyor
    ```
    Installs the **all** variant with every database driver.

    ### Download Binary
    Download the appropriate archive for your platform and database from the assets below.

    ### Verify Checksums
    ```bash
    sha256sum -c dbsurveyor_{{ .Version }}_checksums.txt
    ```

    ### Verify Signatures
    ```bash
    cosign verify-blob \
      --certificate-identity-regexp="https://github.com/EvilBit-Labs/dbsurveyor/.*" \
      --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
      --certificate dbsurveyor_{{ .Version }}_checksums.txt.pem \
      --signature dbsurveyor_{{ .Version }}_checksums.txt.sig \
      dbsurveyor_{{ .Version }}_checksums.txt
    ```

# Source tarball (disabled -- use git clone instead)
source:
  enabled: false
