# Exclude patterns for sensitive files and build artifacts
exclude = [
    "venv/**",
    "**/node_modules/**",
    "**/*.txt",
    "**/*.mdc",
    "**/*.tpl.md",
    "**/CHANGELOG.md",
    "rust_migration/index.md",
    "**/.env",
    "**/*.env",
    "**/*.sql",
    "**/*.sql.gz",
    "**/*.dump",
    "**/*.sqlite",
    "**/*.db",
    "**/*.bak",
    "**/*.backup",
    "**/*.pem",
    "**/*.key",
    "**/*.crt",
    "**/*.pgpass",
    "**/dump/**",
    "**/backups/**",
]
validate = true
number = true
wrap = "keep"
end_of_line = "lf"
extensions = [
    "gfm",
    "frontmatter",
    "footnote",
    "simple_breaks",
    "tables",
    "gfm_alerts",
    "toc",
    "wikilink",
]


[plugin.mkdocs]
align_semantic_breaks_in_lists = true
ignore_missing_references = true
