# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

APPLY_FIXES: none

DISABLE:
    - COPYPASTE # There's just too much copy-paste in the codebase to be worth checking
    - SPELL # It's a spell checker, not a grammar checker

DISABLE_LINTERS:
    - EDITORCONFIG_EDITORCONFIG_CHECKER # We'll come back to this later
    - REPOSITORY_SECRETLINT # Just an endless stream of false positives. Every test and every example has a fake secret in it that it will complain about.
    - REPOSITORY_TRIVY # Doesn't work in CI, just crashes.

ACTION_ACTIONLINT_FILTER_REGEX_EXCLUDE: ".*release\\.yml$"

SHOW_ELAPSED_TIME: true
