# .pre-commit-config.yaml

repos:
  # 🧼 Standard code cleanup hooks (language agnostic)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # 🦀 Rust clippy linting (strict security-focused)
  - repo: local
    hooks:
      - id: rust-clippy
        name: rust-clippy
        entry: cargo clippy -- -D warnings
        language: system
        pass_filenames: false
        always_run: true
        types: [rust]

  # 🦀 Rust formatting
  - repo: local
    hooks:
      - id: rust-fmt
        name: rust-fmt
        entry: cargo fmt -- --check
        language: system
        pass_filenames: false
        always_run: true
        types: [rust]

  # 🔒 Cargo security audit
  - repo: local
    hooks:
      - id: cargo-audit
        name: cargo-audit
        entry: cargo audit
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual]

  # 🧪 GitHub Actions validation
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        files: ".github/workflows/"

  # 🐚 Shell script validation
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck

  # 📝 Commit message linting (commit-msg only, not blocking push)
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # 📝 Markdown formatting and linting
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-admon
          - mdformat-config
          - mdformat-footnote
          - mdformat-frontmatter
          - mdformat-simple-breaks
          - mdformat-tables
          - mdformat-web
          - mdformat-wikilink
          - mdformat-ruff
          - mdformat-gfm-alerts
          - mdformat-rustfmt
          - mdformat-toc

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: ["-c", ".markdownlint-cli2.jsonc"]
