# Cargo audit configuration
# This file documents security advisory ignores with rationale and review dates

[ignore]
# RUSTSEC-2023-0071: MySQL driver vulnerability
#
# Rationale: This advisory affects the mysql crate which is only used when the mysql
# feature is explicitly enabled. The mysql feature is intentionally excluded from
# default features and CI builds for security reasons.
#
# Mitigation:
# - mysql feature is disabled by default
# - CI builds use --no-default-features to avoid mysql
# - Only enabled when explicitly needed for MySQL support
# - Will be removed when mysql crate releases a fix
#
# Owner: UncleSp1d3r
# Review Date: 2025-08-31
# Expiration: 2026-02-28 (6 months from review)
RUSTSEC-2023-0071 = { reason = "mysql feature disabled by default, only used when explicitly enabled", expires = "2026-02-28" }
