[cargo-dist]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]
installers = ["shell", "powershell"]
checksum = "sha256"

# Enable GitHub releases
[cargo-dist.github-releases]
enabled = true

# Optional Homebrew integration (can be enabled later)
[cargo-dist.homebrew]
enabled = false
