
# Several tools are pinned to "latest" to enable the idiomatic version file support. The version is managed by a version file.
[tools]
go                          = "1.26.1"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck"                      = "latest"
"cargo:mdbook"              = "0.5.2"
"cargo:mdbook-linkcheck"    = "0.7.7"
"cargo:mdbook-tabs"         = "0.3.4"
"cargo:mdbook-mermaid"      = "0.17.0"
"cargo:mdbook-toc"          = "0.15.3"
"cargo:mdbook-admonish"     = "1.20.0"
"cargo:mdbook-open-on-gh"   = "3.0.0"
"cargo:mdbook-i18n-helpers" = "0.4.0"
just                        = "latest"
python                      = "latest"
"pipx:mdformat"             = { version = "1.0.0", uvx_args = "--with mdformat-gfm --with mdformat-config --with mdformat-footnote --with mdformat-front-matters --with mdformat-simple-breaks --with mdformat-web --with mdformat-wikilink --with mdformat-gfm-alerts --with mdformat-toc" }
actionlint                  = "1.7.12"
markdownlint-cli2           = "0.22.1"
"cargo:git-cliff"           = "2.13.1"
scorecard                   = "5.5.0"
"pipx:pre-commit"           = "latest"
"bun"                       = "latest"
shellcheck                  = "0.11.0"
goreleaser                  = "2.15.4"

# Many of these settings are defaults, but we are explicit in case they change in the future and to make it clear to users what is enabled.
[settings]
activate_aggressive                 = true
idiomatic_version_file_enable_tools = [ "python", "bun" ]
env_cache                           = true
exec_auto_install                   = true
github_attestations                 = true
lockfile                            = true
pin                                 = true
slsa                                = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true

[env]
ECC_DISABLED_HOOKS = "pre:bash:gateguard-fact-force,pre:edit-write:gateguard-fact-force"
_.file             = [ '.env', ".env.local" ]
