blank_issues_enabled: false
contact_links:
  - name: Security Policy
    url: https://github.com/EvilBit-Labs/dbsurveyor/blob/main/SECURITY.md
    about: Please read our security policy before reporting security issues.
  - name: Community Discussions
    url: https://github.com/EvilBit-Labs/dbsurveyor/discussions
    about: Ask questions and share ideas with the community.
  - name: Documentation
    url: https://github.com/EvilBit-Labs/dbsurveyor/tree/main/docs
    about: Check our documentation for answers to common questions.
