[package]
name = "dbsurveyor-collector"
description = "Database schema and metadata collection tool for offline analysis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "dbsurveyor-collector"
path = "src/main.rs"

[dependencies]
# Workspace dependencies
dbsurveyor-shared = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# CLI-specific dependencies will be added as needed
# clap = { version = "4.0", features = ["derive", "env", "color"] }
# Database connectivity will be feature-gated
# sqlx = { version = "0.8", optional = true, default-features = false }

[lints]
workspace = true
