# Nextest configuration for DBSurveyor
# This file configures cargo-nextest for enhanced test execution

[store]
# Store test results for analysis
dir = "target/nextest"

[profile.default]
# Default profile for local development
retries = 2
test-threads = 4
failure-output = "immediate"
success-output = "never"
status-level = "pass"

[profile.ci]
# Profile optimized for CI environments
retries = 3
test-threads = 2
failure-output = "immediate"
success-output = "final"
status-level = "all"
# Slower timeout for CI environments
slow-timeout = { period = "120s", terminate-after = 2 }

[profile.dev]
# Profile for local development with faster feedback
retries = 1
test-threads = 8
failure-output = "immediate"
success-output = "never"
status-level = "pass"
# Faster timeout for development
slow-timeout = { period = "60s", terminate-after = 1 }

# Test groups for different types of tests
[test-groups]

# Security tests should run sequentially to avoid interference
[test-groups.security]
max-threads = 1

# Integration tests with database containers need limited parallelism
[test-groups.integration]
max-threads = 2

# Unit tests can run with high parallelism
[test-groups.unit]
max-threads = 8

# Override settings for specific test patterns
[[profile.default.overrides]]
filter = "test(security) or test(encryption) or test(credential)"
test-group = "security"

[[profile.default.overrides]]
filter = "test(integration) or test(postgres) or test(mysql) or test(sqlite) or test(mongodb)"
test-group = "integration"

[[profile.default.overrides]]
filter = "not test(security) and not test(encryption) and not test(credential) and not test(integration) and not test(postgres) and not test(mysql) and not test(sqlite) and not test(mongodb)"
test-group = "unit"

# CI profile overrides (same as default but with different retry/thread settings)
[[profile.ci.overrides]]
filter = "test(security) or test(encryption) or test(credential)"
test-group = "security"

[[profile.ci.overrides]]
filter = "test(integration) or test(postgres) or test(mysql) or test(sqlite) or test(mongodb)"
test-group = "integration"

[[profile.ci.overrides]]
filter = "not test(security) and not test(encryption) and not test(credential) and not test(integration) and not test(postgres) and not test(mysql) and not test(sqlite) and not test(mongodb)"
test-group = "unit"

# Dev profile overrides (same as default but with different retry/thread settings)
[[profile.dev.overrides]]
filter = "test(security) or test(encryption) or test(credential)"
test-group = "security"

[[profile.dev.overrides]]
filter = "test(integration) or test(postgres) or test(mysql) or test(sqlite) or test(mongodb)"
test-group = "integration"

[[profile.dev.overrides]]
filter = "not test(security) and not test(encryption) and not test(credential) and not test(integration) and not test(postgres) and not test(mysql) and not test(sqlite) and not test(mongodb)"
test-group = "unit"
